### ISSUE TITLE
KeepLastFragment setting throws an unexpected error

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#11]
If the setting "Keep last fragment in pipelining" is set to "true", a pipeline fragmentation results in an unexpected error.

**Comment by JonasSchaub** [comment]
@FelixBaensch do you maybe see a time slot next week where we can discuss this issue?

**Comment by JonasSchaub** [comment]
@JonasSchaub think about removing this setting all together, this can be handled by the fragmenters now (returned fragments setting). If it should be kept internally for now, set it to false.
