### ISSUE TITLE
Create Mac Native app release

### ISSUE THREAD

**Issue by Kohulan** [FelixBaensch/MORTAR#122]
The mac version of Java has a command line app called jpackage which builds native Mac Apps. If you are in the folder of the fat mortar jar, all you need to do is:

jpackage -i . -n Mortar --icon mortar.icns --main-jar MORTAR-fat-aarch64-1.2.0.0-beta.jar

Note: Make sure Java 21 installed when you build it.

**Comment by JonasSchaub** [comment]
Todo:

- add this to the "how to create a release" instructions
- add the Mac app icon file to the repo
- add a description of this to the "installation" sections in readme and tutorial

**Comment by JonasSchaub** [comment]
jpackage -i . -n MORTAR --icon MORTAR-icon.icns --main-jar MORTAR-fat-aarch64-1.2.0.0.jar
