### ISSUE TITLE
Copying fragments from the fragments tab copies parent structure

### ISSUE THREAD

**Issue by ToLeWeiss** [FelixBaensch/MORTAR#135]
After the fragmentation of a molecule, it is not possible to copy fragments from the "Fragments" tab in the "Structure" column.

### Steps to reproduce:
1. load one or more molecules into MORTAR
2. make a fragmentation of your choice via the lower left button with the algorithm name
3. navigate to the "Fragments" tab
4. copy a fragment from the Structure column, by right clicking on the picture and clicking copy, like shown in the picture

![2024-10-25_15-09](https://github.com/user-attachments/assets/60d04bb3-062f-4579-9575-815cf1e56108)

6. open the file explorer of your choice and paste the picture (png file) into an directory
7. if you open the pasted picture, it shows the parent structure and not the fragment copied

**Comment by FelixBaensch** [comment]
See #136
