### ISSUE TITLE
Look into release-please and whether the MORTAR release assets, the two fat JARs and the .dmg files, could be generated automatically using this

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#138]

**Comment by FelixBaensch** [comment]
?

**Comment by JonasSchaub** [comment]
With the v1.2.1 release (#137 ), I'm also completing https://github.com/FelixBaensch/MORTAR/issues/122 but generating these .dmg files for Mac is not really sustainable since they can only be generated *on a MacBook* and also only for the specific processor architecture. So, generating the .dmg file for a non-M1 or pre-M1 MacBook, requires such a MacBook (and only one person in our group has one still).
So, either there is a way to automate this with GitHub actions, e.g. via release-please, or I will drop the non-M1 .dmg deployment option from future MORTAR releases.
Something to look into after GCC.

**Comment by FelixBaensch** [comment]
Makes sense, I stumbled across ‘release-please’.

**Comment by JonasSchaub** [comment]
The two new .yml files (mac-deployment.yml and mac-deployment-aarch64.yml) on production successfully generate the two .dmg files which can be downloaded and then included in the release. 
Automating the entire release creation is impossible because the Excelsior Installer package needs to be created manually anyway. And since the two fat JARs are created locally for this purpose anyway, I see no sense in automating their creation via .yml files as well.
I will close this issue now and figure out how to best make the MORTAR v1.2.1 release now finally tomorrow.
