### ISSUE TITLE
Activate GitHub pages for this repo, building from branch "gh-pages"

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#20]
We can use the readme as landing page and put the tutorial there. Even more tutorials or documentation material in the future.

I have started the gh-pages branch from the current master commit now (instead of an orphan branch, which would be best practice). So, we have to think about what to remove from this branch. But I first wanted to have a look at how the different files are displayed in this environment.

**Comment by FelixBaensch** [comment]
What should/can I do here?

**Comment by FelixBaensch** [comment]
Thank you, I didn't realize that I had to do that, I thought you were allowed to do that too.
Btw.: Done
https://felixbaensch.github.io/MORTAR/

**Comment by JonasSchaub** [comment]
> I thought you were allowed to do that too.

Sadly, no...

> Btw.: Done

Thanks, I will look at it and improve it a bit.

**Comment by JonasSchaub** [comment]
Done, stripped all unnecessary files from the gh-pages branch, fixed the logo, added link to online version of tutorial PDF document: https://felixbaensch.github.io/MORTAR/
