### ISSUE TITLE
Update javafxplugin to 0.1.0

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#23]
This created an issue I was unable to solve on the fly, have to look at it later.<br>
There is a note in the readme here https://github.com/openjfx/javafx-gradle-plugin about problems with migrating from 0.0.14 to 0.1.0

**Comment by FelixBaensch** [comment]
Can you specify the issue and how to reproduce it

**Comment by JonasSchaub** [comment]
Reproduction: update javafxplugin in build.gradle to v 0.1.0 and try to build the project. See notes by the developers here: https://github.com/openjfx/javafx-gradle-plugin#migrating-from-0014-to-010
