### ISSUE TITLE
Introduce "production" branch and protect master branch afterwards.

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#27]

**Comment by JonasSchaub** [comment]
About master/main branch protection: I've done this very minimally in one repo now, simply checking the "Require a pull request before merging" option in the branch settings (without checking any sub-options there). Could this be something we do here as well?

**Comment by FelixBaensch** [comment]
I've also enabled "Require status checks to pass before merging" with SonarCloud status check, and "Require status checks to pass before merging".

**Comment by JonasSchaub** [comment]
That might be a bit harsh, we don't always fulfill all the SonarCloud quality gate requirements in terms of test coverage and code duplication 😅

**Comment by JonasSchaub** [comment]
I've created a production branch starting from the current main commit. Please merge your pull requests there from now on.

**Comment by JonasSchaub** [comment]
Thank you, I will notify you again should there be any problems with the main branch protection rule :D
Is it actually transferred from master to main or do you have to adjust that? I think these rules work based on names, not behind-the-scenes branch ids.

**Comment by FelixBaensch** [comment]
It should be transferred automatically

**Comment by FelixBaensch** [comment]
If I see this correctly all PRs where transferred from "master" to "main"
