### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#29]

**Comment by FelixBaensch** [comment]
Does this affect the existing PRs?

**Comment by JonasSchaub** [comment]
> Does this affect the existing PRs?

If you rename the branch here in the remote (Settings -> Default Branch -> Rename Branch), it should not affect PRs, since it is still the same branch. But PRs can also be later configured to point to another branch. The only slight issue is that you/we have to also rename the branch in our local clones or simply check out the new main branch.

> At the same time, the repository could be tidied up, old branches deleted, etc.

Always a good idea.

**Comment by FelixBaensch** [comment]
> If you rename the branch here in the remote
Done 

To change it locally follow:

git branch -m main <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
git remote set-head origin -a


Please mark or delete old, unnecessary branches

**Comment by JonasSchaub** [comment]
"git branch -u origin/" produced "error: the requested upstream branch 'origin/' does not exist" but the local renaming was still successful as it seems, thanks!

**Comment by JonasSchaub** [comment]
GitHub told me to use this:

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

**Comment by JonasSchaub** [comment]
> Please mark or delete old, unnecessary branches

I've looked through the branches and deleted those that were merged and not used afterwards.
