### ISSUE TITLE
Repository clean up

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#30]
Please mark or delete old, unnecessary branches

**Comment by JonasSchaub** [comment]
Done!

There remain only 2 or 3 branches where we tried stuff (like single core fragmentation or keep atom container) where I don't know what to do. Can we mark them as stale or sth?

**Comment by FelixBaensch** [comment]
I am open for both

**Comment by JonasSchaub** [comment]
Both are actually already marked as "stale" as it seems. So I would keep it that way.

The other open branches already have open pull requests that we are going to resolve.

So is this issue completed?
