### ISSUE TITLE
Tab indices do not reset when loading a new file

### ISSUE THREAD

**Issue by SamuelBehr** [FelixBaensch/MORTAR#4]
When loading a new file into MORTAR, the indices attached to the tab names do not reset.

![MORTAR_tabIndicesDoNotResetWhenLoadingNewFile](https://user-images.githubusercontent.com/82887793/218789206-3aa958ca-0664-404a-856f-3fa82229cf51.png)

In this case, there should be no index attached to the file names. But since I already executed a fragmentation on a former file, there is.

Kind regards,

Samuel

**Comment by JonasSchaub** [comment]
Is this a bug or a feature? @FelixBaensch :D

**Comment by FelixBaensch** [comment]
Is fixed and will be included in the next release.
