### ISSUE TITLE
Allow more elements per line in SMILES file

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#40]

**Comment by JonasSchaub** [comment]
Could you elaborate a bit more?

**Comment by FelixBaensch** [comment]
At the moment the SMILES importer is very restrictive and only allows 2 entries per line separated by a separator, i.e. if I have a file with an additional entry, it will not be read. This is not very practical for a "loose" format like a text file containing SMILES.

**Comment by JonasSchaub** [comment]
I think this was actually the point in #31
