### ISSUE TITLE
Rework method and usage of CollectionUtil.sortGivenFragmentListByPropertyAndSortType()

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#50]

**Comment by FelixBaensch** [comment]
What exactly should be improved here?

**Comment by JonasSchaub** [comment]
To quote the comment in line 51: "check parameters, change params to enum values (and bools?), throw exceptions!"
I'll take care of it.

**Comment by FelixBaensch** [comment]
Exactly, I overlooked the comment.
I'll do it, you don't have to do everything.

**Comment by JonasSchaub** [comment]
As you wish 🤷‍♂️ 😄

**Comment by FelixBaensch** [comment]
I don't know what is meant by the "bools", but the rest should be fixed, see  #53

**Comment by FelixBaensch** [comment]
Closed, see #53
