### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#52]
https://github.com/FelixBaensch/MORTAR/blob/9793153bc7dcac7220f76239b9d1612932f478ea/src/main/java/de/unijena/cheminf/mortar/gui/views/ItemizationDataTableView.java#L101

@FelixBaensch , the first parameter "anItemAmount" seems to be unused. Can I safely remove it?

**Comment by FelixBaensch** [comment]
If you customize the call as well

**Comment by JonasSchaub** [comment]
> If you customize the call as well

... of course! But all in all, this is an artifact and the maximum fragment column number for the items tab is now determined in a different way, do I see this correctly?

**Comment by FelixBaensch** [comment]
Yes

https://github.com/FelixBaensch/MORTAR/blob/9793153bc7dcac7220f76239b9d1612932f478ea/src/main/java/de/unijena/cheminf/mortar/gui/views/ItemizationDataTableView.java#L164

**Comment by JonasSchaub** [comment]
Ah, thank you, didn't see that! I'll remove this param then 👍

**Comment by JonasSchaub** [comment]
Resolved by https://github.com/FelixBaensch/MORTAR/pull/49
