### ISSUE TITLE
Overview button too small?

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#54]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/638d9b17-5bbb-4d2d-be1e-8fcfcbe85722)

Linux Mint

**Comment by JonasSchaub** [comment]
I guess the histogram button in the fragments tab looks the same?

**Comment by FelixBaensch** [comment]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/35b783be-4451-4316-8b66-c82a07e23942)

![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/6a9d42e5-7e9b-45b1-9e82-30de56b1db07)

**Comment by JonasSchaub** [comment]
All of these buttons have the MORTAR standard size. I guess this has to be increased then. What do you think?

**Comment by JonasSchaub** [comment]
> this looks like an OS depending problem

...definitely. I've done a quick research and it seems to be discouraged to define a general "look and feel" for a JavaFx app. This way, the app can look "native" in each OS which is nice.

Setting the font can be done via the style sheet, e.g.:
`.root{
    -fx-font-size: 9pt;
}`
Setting the font type would be helpful but would make it harder to port MORTAR to other OS because the specific font might not be installed on the system. But I actually think the font is the bigger problem here than the font size...

**Comment by JonasSchaub** [comment]
Are you starting MORTAR from IntelliJ on your Linux system? Or via the JAR? So how could I give you a version with a defined font size to try it out on your system?

**Comment by JonasSchaub** [comment]
Could you then go to my sonar-issues-fix branch and try it out there? I simply added `.root{ -fx-font-size: 9pt; }` to the style sheet. Feel free to play around with the value.

**Comment by FelixBaensch** [comment]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/84b354df-1a5a-42f0-bf16-35536368a3de)

![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/df12d9f0-4789-4493-8696-8264ad5be802)

![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/ab62fb68-aeaf-4f44-9e7c-aa7404b05ada)

**Comment by FelixBaensch** [comment]
It fixed the overview button on the main page but not the rest

**Comment by JonasSchaub** [comment]
Then we either have to make the buttons bigger or the text even smaller... "Export CSV" and "Export PDF" could also be abbreviated to "CSV" and "PDF". What do you think?

**Comment by FelixBaensch** [comment]
> "Export CSV" and "Export PDF" could also be abbreviated to "CSV" and "PDF". What do you think?

That was my suggestion from the start

**Comment by JonasSchaub** [comment]
I have done that on the same branch as before. I have also exchanged the "Histogram" button label with "Plot". I thought it sounds like a command "plot frequencies" and would fit. I am missing ideas how else to abbreviate the histogram button label. What do you think? And could you please check all the buttons again?

**Comment by JonasSchaub** [comment]
No worries, this week is basically over anyway 😄

**Comment by FelixBaensch** [comment]
CSV and PDF look good to me, "Plot" might be a bit confusing. How about "Hist" or "Histo"?

**Comment by FelixBaensch** [comment]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/8ffabaa8-4fe1-48b7-84da-10652b9469c8)

This looks weird

**Comment by FelixBaensch** [comment]
Looks good
