### ISSUE TITLE
No 3D coordinates dialog not very intuitive

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#57]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/9eaddc2e-89fa-4457-b2b0-f628cfb4c76c)

The fact that the Cancel button here means that no 3D coordinates are generated and not that the export is canceled is not very intuitive and breaks with the rest. It would be better to have a dedicated button and that the cancel button cancels the export.

**Comment by JonasSchaub** [comment]
Fun fact, Windows and Linux arrange the buttons differently:
![image](https://github.com/FelixBaensch/MORTAR/assets/44881147/8f094447-e87f-4c34-a06d-c96bf6a86385)
