### ISSUE TITLE
Illegal Argument Error on start

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#61]
![image](https://github.com/FelixBaensch/MORTAR/assets/57186528/af07d7b6-edc2-4a7a-9394-62f4769f6a1d)

**Comment by JonasSchaub** [comment]
The message should vanish when you restart

**Comment by FelixBaensch** [comment]
I could not reproduce it, but generally this should not happen

**Comment by JonasSchaub** [comment]
Agreed. I will leave this open for now. Please share the full stack trace should it appear again.

**Comment by JonasSchaub** [comment]
I have to add that my changes are compatible in the sense that a new MORTAR version will not throw an exception when encountering an old settings file. But the old version does when encountering a settings file of a new version.
