### ISSUE TITLE
Implement a toogle switch for the boolean settings?

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#66]
The current combo boxes containing "true" and "false" are not very nice. Maybe a nice toggle switch like you see in most mobile apps these days could be implemented? In a very brief research, I found this StackOverflow post: https://stackoverflow.com/questions/30593193/creating-sliding-on-off-switch-button-in-javafx 

There seems to be no JavaFx-native control like that but one could be implemented.

Maybe a nice student project.

**Comment by FelixBaensch** [comment]
Sounds good for a "Laborpraxis"

**Comment by JonasSchaub** [comment]
Look into code of controls fx, they have a toggle switch

**Comment by JonasSchaub** [comment]
Exactly, and I don't want to add it as a dependency. I just wanted to mention the code of the library as another source of "inspiration".

**Comment by JonasSchaub** [comment]
ControlsFx Code: https://github.com/controlsfx/controlsfx/tree/master
