### ISSUE TITLE
Export files without extension

### ISSUE THREAD

**Issue by FelixBaensch** [FelixBaensch/MORTAR#75]
At least under Linux, the exported files lack the file extension.

**Comment by JonasSchaub** [comment]
So if you set as file name for the export sth without a file extension, it is not automatically added?
I've quickly tested it on Windows and it seems like the Windows file chooser handles this automatically and adds the extension.
Good that you spotted this for Linux!

**Comment by JonasSchaub** [comment]
Can be closed?
