### ISSUE TITLE
Menu bar not working when fragmentation is running

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#83]
An effect Kohulan encountered when tunneling MORTAR from a Linux server on a Mac. Investigate!

**Comment by FelixBaensch** [comment]
Is this really a MORTAR error or is it because the GUI is tunneled from the server to the desktop?

**Comment by JonasSchaub** [comment]
Most likely and hopefully the latter. But I need to look into this. Hence the "Investigate!" 😄

**Comment by JonasSchaub** [comment]
I have imported 1000 molecules and set the Scaffold Generator Fragmenter's "fragmentation type setting" to "all sub-scaffolds", so that the fragmentation takes a long time. I could not reproduce the problem reported here, everything worked as expected, I could access all functionalities of the application. So I'm going to close this issue.
