### ISSUE TITLE
Add section to tutorial about the possibility to run MORTAR remotely on a server and tunnel the GUI to desktop using X

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#85]
Kohulan got this to work.
General: https://www.baeldung.com/linux/forward-x-over-ssh
Kohulan used XQuartz: https://www.xquartz.org

**Comment by FelixBaensch** [comment]
To be honest, I would simply mention that this is possible and then refer to the references. This is not something that only works explicitly with MORTAR, it should work with "any" application.

**Comment by JonasSchaub** [comment]
That was basically my intention as well 👍

**Comment by JonasSchaub** [comment]
@FelixBaensch , what do you think?

"The [X / X11 / X Window System](https://www.x.org/wiki/) can be used to run a graphical application like MORTAR on a remote server while displaying the graphical user interface on the local machine / personal computer. This setup can be beneficial if more computing power or memory is required to analyse large data sets. However, please note that while this is possible in principle, unexpected behaviour from MORTAR may occur. We cannot take responsibility for or recommend this way of deployment, similar to using the WSL as mentioned above." (added in the installation section after the instructions for Linux/Mac)

**Comment by FelixBaensch** [comment]
If you really want to mention it, then the paragraph is good

**Comment by JonasSchaub** [comment]
It may be helpful for people. Until we have a "MORTAR CMD/CLI" version that can run on servers or in the cloud, this is the only way to run MORTAR on remote machines without a graphical interface. And Kohulan got it to work quite easily.
