### ISSUE TITLE
Fragmenter settings in the pipeline view reflect back to the general fragmentation settings for the respective fragmenter.

### ISSUE THREAD

**Issue by JonasSchaub** [FelixBaensch/MORTAR#88]

**Comment by FelixBaensch** [comment]
Can you describe this in more detail and perhaps give an example of reproducibility?

**Comment by JonasSchaub** [comment]
Open MORTAR -> Fragmentation Settings -> check a specific setting of a specific fragmenter -> pipeline dialog, click default, add a first fragmenter of the same algorithm -> open its settings and change the setting there -> apply -> apply -> Fragmentation Settings of the fragmenter => the setting has also changed its value there.

I guess I just have to make a copy instead of a reference in the pipeline view controller. I will take care of it.

**Comment by FelixBaensch** [comment]
Thanks, for clarifying, I had tested it with an existing pipeline. 
Exactly, either a copy or a new instance of the fragmenter. But that should have worked once.
